<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Thu, 19 Mar 2026 19:25:22 -0400
 */
$conf['title'] = 'Paul Alejandro Castedo Arteaga';
$conf['lang'] = 'es';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['savedir'] = '/app/www/public/data';
