# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 19 Mar 2026 19:25:22 -0400
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

morgon:$2y$10$Av9XLBgBFq3WXSQK5tvNAeArEJty1il8wXCns7K0nf5HkFfUTBTq.:Paul:p@upds.bo.com:admin,user
